x-db-variables: &env-config
  POSTGRES_DB: ${POSTGRES_NAME}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  HOST: ${HOST}
  EXCHANGE_NAME: ${EXCHANGE_NAME}
services:
  machine-a-laver1:
    container_name: 'machine-a-laver-1'
    build:
      context: .
      dockerfile: src/main/java/com/laverie/machine/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      <<: *env-config
      ID: ${MACHINE1_ID}
    networks:
      - laverie-net

  machine-a-laver2:
    container_name: 'machine-a-laver-2'
    build:
      context: .
      dockerfile: src/main/java/com/laverie/machine/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      <<: *env-config
      ID: ${MACHINE2_ID}
    networks:
      - laverie-net

  machine-a-laver3:
    container_name: 'machine-a-laver-3'
    build:
      context: .
      dockerfile: src/main/java/com/laverie/machine/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      <<: *env-config
      ID: ${MACHINE3_ID}
    networks:
      - laverie-net

  tel-admin:
    container_name: 'TelAdmin'
    build:
      context: .
      dockerfile: src/main/java/com/laverie/admin/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      <<: *env-config
      MACHINE1_ID: ${MACHINE1_ID}
      MACHINE2_ID: ${MACHINE2_ID}
      MACHINE3_ID: ${MACHINE3_ID}
    networks:
      - laverie-net

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:4.2.2-management-alpine
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - laverie-net

  db:
    image: postgres:16-alpine
    container_name: 'laverie_db'
    environment:
      <<: *env-config
    volumes:
      - laverie_db:/var/lib/postgresql/data
      - ./laverie_db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}" ]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - laverie-net

volumes:
  rabbitmq_data:
  laverie_db:

networks:
  laverie-net:
    driver: bridge